### ISSUE TITLE
[2Xpt] Create music Class and implement all methods [Student B]

### ISSUE THREAD

**Issue by muneeb3123** [muneeb3123/ruby-capstone#25]
- Create MusicAlbum class in a separate .rb file.
- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:

- can_be_archived?() in the MusicAlbum class
should override the method from the parent class
should return true if parent's method returns true AND if on_spotify equals true
otherwise, it should return false

**Comment by LarryIVC** [comment]
### Hi @flemton 🙋‍♀️,  

Excellent work! 💯 
You have done a great job. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## Highlights 🌞 

✔️  Good PR title and description
✔️  Great implementation

# Status: Approved ✔️ 

![oscars-standing-ovation](https://user-images.githubusercontent.com/38088818/164766743-7f6493f3-4506-4331-9678-207bad27e7f5.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
